#!/bin/bash

xinput set-prop `xinput list | grep TouchPad | grep -Eo 'id=[0-9]+' | tr -d 'id='` "libinput Disable While Typing Enabled" 0
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0
xinput set-prop `xinput list | grep Touchpad | grep -Eo 'id=[0-9]+' | tr -d 'id='` "libinput Disable While Typing Enabled" 0

xinput set-prop `xinput list | grep TouchPad | grep -Eo 'id=[0-9]+' | tr -d 'id='` "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop `xinput list | grep Touchpad | grep -Eo 'id=[0-9]+' | tr -d 'id='` "libinput Tapping Enabled" 1
