#!/bin/sh

echo Mapping tablet to VGA-1
for device in `xinput | ~/dev/system/map-tablet.py`; do
    xinput map-to-output $device VGA-1;
done

# krita - undo
xsetwacom set "HID 256c:006e Pad pad" Button 10 "key ctrl z"
# krita - redo
xsetwacom set "HID 256c:006e Pad pad" Button 9 "key ctrl shift z"
# krita - open brush selector
xsetwacom set "HID 256c:006e Pen stylus" Button 3 "key ctrl shift p"
